### ISSUE TITLE
Workflow 엔진 모니터링 도구에 서비스 이름 표시

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/concert_workflow_engine#11]
사용중인 모니터링 도구에서 현재 작동중인 프로세스 의 이름이 id로만 표시되어 있습니다. 
혹시 이 부분은 어떤 워크플로우들이 동작하고 있는지 또는, 어떤 서비스 이름으로 프로세스가 동작하고 있는지 알 수 있는 방법이 있으면 좋을것 같습니다.

**Comment by eskim** [comment]
서비스 이름 노출하는 부분은 이미 작업이 되어 있었는데 버그가 있어 수정했습니다.
실행 중인 워크플로우 목록이 보여주는 부분은 이미 작업이 되어 있는데 출력이 되지 않고 있나요?

**Comment by dwlee** [comment]
출력되지 않고 점만 찍혀 있는 상황입니다.

**Comment by eskim** [comment]
닫겠습니다.
