### ISSUE TITLE
Timeout 분리 

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/concert_workflow_engine#17]
워크플로우 저작시, 자원 할당할때 timeout을 설정할 수 있습니다. 
이 때 설정하는 timeout은 자원의 할당 시간 + 자원의 사용 시간을 포함합니다. 
이 부분을 분리해야 합니다. 
- 자원 사용시간에 대한 timeout
  - 워크플로우에서 자원 할당시 설정하는 timeout
  - 자원 할당 성공부터 시간을 체크합니다. 만약 timeout 시 에러를 처리할 수 있도록 합니다. 
    (현재 자원 할당시 성공, 실패 두가지 케이스만 있는데 성공, 실패, timeout 세가지 케이스에 대해 고려할 수 있어야 합니다. )
-  자원 할당시간에 대한 timeout
  - 엔진 시작시 환경설정에서 읽어와 설정하는 timeout
  - 자원할당 요청에서 부터 자원 할당 완료까지 체크합니다.  
  - 다음과 같이 환경 설정을 추가하여, 자원의 할당시간에 대한 timeout을 설정해야 합니다. 

```
CONCERT_WORKFLOW_ENGINE_RES_ALLOCATION_TIMEOUT (default: 6000s )
```

**Comment by jihoonl** [comment]
Resource timeout은 서비스마다 다르게 설정될수 있습니다. 서비스 파라메터에서 받아서 쓰는게 어떨까요

**Comment by dwlee** [comment]
Resource timeout은 자원 사용시간에 대한 timeout을 의미하나요? 아니면 자원 할당시간에 대한 timeout을 의미하나요?

**Comment by eskim** [comment]
자원 사용 timeout 부분이 이해가 되지 않습니다. 할당후의 사용 시간을 timeout 으로 처리해야하는 경우가 어떤 것이 있을까요?

timeout 후에는 자원을 해제해야 하는 것인가요?

**Comment by dwlee** [comment]
예를들어 배달 서비스의 경우, 배달 중 로봇이 어떤 이유로 action에 대한 result 없이 멈췄을때 워크플로우에서는 알 수있는 방법이 없습니다. 그래서 워크플로우 쪽에서 자원의 사용시간에 대한 timeout을 두어 이 시간동안 자원이 해제되지 않으면 timeout에러를 내는것입니다. 자원 해제는 워크플로우에 해제 블럭을 사용해도 되고, 엔진에서 timeout 발생시 해제 해도 상관 없습니다.

**Comment by eskim** [comment]
@dwlee 네 알겠습니다. 할당에 대한 timeout 은 현재 저작시 블럭의 설정하는 부분은 할당에 대한 부분의 timeout 입니다. 환경변수로 처리해야할 timeout 과 블럭의 설정으로 처리할 timeout 을 명확히 분리해 주시면 작업 진행하겠습니다.

그리고 @jihoonl 의 아이디어는 어떻게 얘기가 된 부분이 있는지요? 더 의논이 필요하면 작업을 조금 미루도록 하겠습니다.

**Comment by dwlee** [comment]
이 이슈는 다음과 같이 진행되기로 결정되었습니다. 
- 자원 할당시간에 대한 timeout
  - 해당 워크플로우에서 rapp 을 할당하여 사용하는 부분이 있다면 서비스 저작시 resource_allocation_ timeout 이라는 parameter가 자동으로 추가되도록 합니다. 물론, 기본값도 포함되도록 합니다. 
- 자원 사용시간에 대한 timeout
  - 기존의 자원할당 블럭에서 config에 timeout을 설정하는 부분을 제거 합니다. 
  - 자원 할당블럭에 [설정가능한 블럭](https://github.com/robotics-in-concert/concert_workflow_engine/issues/18)을 껴 넣을수 있도록 합니다. 
  - 서비스 저작시 이 블럭에 대한 값을 설정합니다. 

위 내용은 설정가능한 블럭이 먼저 개발되어야 가능함 시나리오 입니다.

**Comment by dwlee** [comment]
완료하였습니다.
