### ISSUE TITLE
emit error

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/concert_workflow_engine#8]
다음과 같은 에러가 발생합니다. 

```
info: engine-8232 error in fiber [TypeError: Cannot call method 'emit' of undefined]
```

해당 워크플로우는 
http://composer.robotconcert.org:9999/#/blockly 의 pickup delivery wf 를 참고하면 됩니다.

**Comment by eskim** [comment]
prezi 코드에서 발생한 문제가 맞습니다. 생각보다 문제가 간단하지 않아 수정에 시간이 좀 걸릴듯 합니다.
급하시면 우선 prezi 관련 코드는 없애고 작업 진행 부탁드립니다.
